events {}

http {
    upstream backend_pool {
        server 172.21.0.11:3000;
        server 172.21.0.12:3000;
    }

    server {
        listen 80;
        server_name app.groupx.lab;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name app.groupx.lab;

        ssl_certificate     /certs/gateway.crt;
        ssl_certificate_key /certs/gateway.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
